process.env.SERVICE_ID = 'M2';
import { bootstrap } from '../../shared/src/bootstrap';
import { CartSkeletonController } from './cart/cart.skeleton.controller';
import { OrderSkeletonController } from './order/order.skeleton.controller';
import { VoucherSkeletonController } from './voucher/voucher.skeleton.controller';
import { PaymentSkeletonController } from './payment/payment.skeleton.controller';
import { ReportSkeletonController } from './report/report.skeleton.controller';
import { SePayController } from './payment/sepay.controller';
import { ReviewEligibilityInternalController } from './order/review-eligibility.internal.controller';
bootstrap('M2',[ReviewEligibilityInternalController,SePayController,CartSkeletonController,OrderSkeletonController,VoucherSkeletonController,PaymentSkeletonController,ReportSkeletonController]).catch(()=>{ console.error('Startup failed: check service configuration and dependencies.'); process.exit(1); });
