"""Render the task board from GitHub Issues; credentials stay in the environment."""
import argparse
import html
import json
import os
from pathlib import Path
import re
import urllib.error
import urllib.parse
import urllib.request

ROOT = Path(__file__).resolve().parents[1]
OWNERS = {'cong': 'Công', 'hoa': 'Hoa', 'tri': 'Trí', 'thinh': 'Thịnh', 'hatsaphone': 'Hatsaphone'}
COLUMNS = [('backlog', 'Backlog'), ('todo', 'Todo'), ('in-progress', 'In progress'),
           ('review', 'Review'), ('blocked', 'Blocked'), ('done', 'Done')]
OPEN_STATUSES = {name for name, _ in COLUMNS if name != 'done'}


def fetch_issues(repo):
    headers = {'Accept': 'application/vnd.github+json', 'User-Agent': 'PBL6-Kanban', 'Cache-Control': 'no-cache',
               'X-GitHub-Api-Version': '2022-11-28'}
    token = os.environ.get('GITHUB_TOKEN')
    if token:
        headers['Authorization'] = 'Bearer ' + token
    result = []
    for page in range(1, 101):
        # Filter labels after fetching: a newly added label can lag in API filtering.
        url = f'https://api.github.com/repos/{repo}/issues?state=all&sort=created&direction=asc&per_page=100&page={page}'
        with urllib.request.urlopen(urllib.request.Request(url, headers=headers), timeout=30) as response:
            batch = json.load(response)
        result.extend(issue for issue in batch if 'pull_request' not in issue)
        if len(batch) < 100:
            return result
    raise RuntimeError('Too many issue pages; refusing to publish a partial board')


def escape(value):
    text = html.escape(' '.join(str(value).split()), quote=False)
    return re.sub(r'([\\|\[\]`*_])', r'\\\1', text)


def render(repo, issues, definitions):
    order = {task['id']: index for index, task in enumerate(definitions)}
    groups = {name: [] for name, _ in COLUMNS}
    warnings, cancelled = [], []
    for issue in issues:
        if 'pull_request' in issue:
            continue
        labels = {label['name'] for label in issue.get('labels', [])}
        if 'task' not in labels:
            continue
        number = int(issue['number'])
        marker = re.search(r'<!-- pbl6-task:([A-Z0-9-]+) -->', issue.get('body') or '')
        prefix = re.match(r'^\[([A-Z0-9-]+)\]', issue['title'])
        task_id = marker.group(1) if marker else prefix.group(1) if prefix else f'TASK-{number}'
        owners = [OWNERS[key] for key in OWNERS if f'owner:{key}' in labels]
        owner = ', '.join(owners) if owners else 'Chưa phân công'
        if len(owners) != 1:
            warnings.append(f'#{number}: cần đúng một label owner.')
        states = {label.removeprefix('status:') for label in labels if label.startswith('status:')}
        if issue['state'] == 'closed' and issue.get('state_reason') == 'not_planned':
            cancelled.append((number, issue['title'], owner))
            continue
        if issue['state'] == 'closed':
            status = 'done'
        elif len(states) == 1 and next(iter(states)) in OPEN_STATUSES:
            status = next(iter(states))
        else:
            status = 'blocked'
            warnings.append(f'#{number}: cần đúng một status mở hợp lệ; Done chỉ khi issue đóng hoàn thành.')
        title = re.sub(r'^\[[A-Z0-9-]+\]\s*', '', issue['title'])[:180]
        groups[status].append({'id': task_id, 'number': number, 'title': title, 'owner': owner})
    for group in groups.values():
        group.sort(key=lambda task: (order.get(task['id'], len(order)), task['number']))
    url = f'https://github.com/{repo}'
    filters = lambda query: url + '/issues?q=' + urllib.parse.quote(query, safe='')
    lines = ['# Kanban phân việc PBL6', '',
             '<!-- Generated by scripts/sync_kanban.py from GitHub Issues. Do not edit status here. -->', '',
             f'Nguồn trạng thái: [GitHub Issues]({filters("is:issue label:task")}). '
             'Bảng được cập nhật khi task/label/assignee thay đổi; cách dùng ở [Kanban guide](kanban-guide.md).', '',
             '**Owner thực hiện:** label `owner:*` theo tên member. **Assignee:** xem tài khoản hiện được giao trong từng issue. '
             'Có username chưa đồng nghĩa đã nhận lời mời cộng tác.', '',
             '[GitHub Projects kéo thả](https://github.com/users/embetapbay123/projects/1/views/2) '
             'được đồng bộ thủ công từ issue bằng `python scripts/sync_project.py`; xem hướng dẫn trước khi đổi trạng thái.', '',
             '| ' + ' | '.join(f'{title} ({len(groups[name])})' for name, title in COLUMNS) + ' |',
             '| ' + ' | '.join('---' for _ in COLUMNS) + ' |']
    for index in range(max((len(group) for group in groups.values()), default=0)):
        row = []
        for name, _ in COLUMNS:
            if index >= len(groups[name]):
                row.append('—')
                continue
            task = groups[name][index]
            row.append(f'**{escape(task["id"])} · {escape(task["owner"])}**<br>'
                       f'[#{task["number"]} {escape(task["title"])}]({url}/issues/{task["number"]})')
        lines.append('| ' + ' | '.join(row) + ' |')
    config = json.loads((ROOT/'docs/implementation/github-project.json').read_text(encoding='utf-8'))
    lines.extend(['', '## Lọc nhanh theo người', '', '| Owner | GitHub | Task |', '| --- | --- | --- |'])
    for key, owner in OWNERS.items():
        account = config['members'].get(key)
        profile = f'[@{account}](https://github.com/{account})' if account else 'Chưa có username'
        lines.append(f'| {owner} | {profile} | [Xem task mở]({filters("is:issue is:open label:task label:owner:" + key)}) |')
    lines.extend(['', '## Lọc theo trạng thái', ''])
    for name, title in COLUMNS:
        query = 'is:issue label:task ' + ('is:closed reason:completed' if name == 'done' else f'is:open label:status:{name}')
        lines.append(f'- [{title}]({filters(query)})')
    if warnings:
        lines.extend(['', '## Metadata cần sửa', ''])
        lines.extend('- ' + escape(warning) for warning in warnings)
    if cancelled:
        lines.extend(['', '## Task đóng vì không thực hiện', '', 'Các task này không được tính Done.', ''])
        for number, title, owner in cancelled:
            lines.append(f'- [#{number} {escape(title)}]({url}/issues/{number}) — {escape(owner)}')
    lines.extend(['', 'Task chưa hoàn thành vẫn giữ mở. Khi đủ nghiệm thu và PR đã merge, đóng issue với reason '
                  '`completed`; PR có `Closes #N` sẽ đóng issue khi merge. '
                  'Không đổi endpoint-status chỉ vì kéo task sang một trạng thái mới.', ''])
    return '\n'.join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--repo', default=os.environ.get('GITHUB_REPOSITORY', 'embetapbay123/PBL6'))
    parser.add_argument('--input', type=Path, help='Offline GitHub Issues JSON snapshot')
    args = parser.parse_args()
    if not re.fullmatch(r'[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+', args.repo):
        raise SystemExit('Invalid repository slug')
    definitions = json.loads((ROOT/'docs/implementation/kanban-tasks.json').read_text(encoding='utf-8'))
    try:
        issues = json.loads(args.input.read_text(encoding='utf-8')) if args.input else fetch_issues(args.repo)
        content = render(args.repo, issues, definitions)
    except urllib.error.HTTPError as error:
        raise SystemExit(f'GitHub request failed: HTTP {error.code}; board was not changed') from None
    target = ROOT/'docs/implementation/kanban.md'
    previous = target.read_text(encoding='utf-8') if target.exists() else None
    if previous != content:
        target.write_text(content, encoding='utf-8', newline='\n')
    print('Kanban updated' if previous != content else 'Kanban unchanged')


if __name__ == '__main__':
    main()
